/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "portc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	RCC_AHB1ENR |=(1<<1);
	RCC_AHB1ENR |=(1<<2);
	RCC_AHB1ENR |=(1<<0);

	GPIOB_MODER &=~(1<<30);
	GPIOB_MODER |=(1<<30);


	GPIOC_MODER &=~(1<<12);
	GPIOC_MODER |=(1<<12);

	GPIOB_MODER &=~(1<<28);
	GPIOB_MODER |=(1<<28);

	GPIOB_MODER &=~(1<<26);
	GPIOB_MODER |=(1<<26);



	GPIOB_MODER &=~(1<<14);
	GPIOB_MODER &=~(1<<6);
	GPIOB_MODER &=~(1<<8);
	GPIOA_MODER &=~(1<<30);

	GPIOB_ODR |=(1<<13);
	GPIOB_ODR |=(1<<14);
	GPIOB_ODR |=(1<<15);
	GPIOC_ODR |=(1<<6);






    /* Loop forever */
	for(;;){
		int i;
		//switch 1 and 1 LED
		if(!(GPIOB_IDR &=(1<<7))){
			for(i=0;i<300000;i++){
				if(!(GPIOB_IDR &=(1<<7))){
					GPIOC_ODR ^=(1<<6);
				}
				for(i=0;i<300000;i++);
			}
		}
		//switch 2 and 2 LED's
		if(!(GPIOB_IDR &=(1<<3))){
					for(i=0;i<300000;i++){
						if(!(GPIOB_IDR &=(1<<3))){
							GPIOC_ODR ^=(1<<6);
							GPIOB_ODR ^=(1<<15);
						}
						for(i=0;i<300000;i++);
					}
				}
		//switch 3 and 3 LED's
		if(!(GPIOB_IDR &=(1<<4))){
							for(i=0;i<300000;i++){
								if(!(GPIOB_IDR &=(1<<4))){
									GPIOC_ODR ^=(1<<6);
									GPIOB_ODR ^=(1<<15);
									GPIOB_ODR ^=(1<<14);
								}
								for(i=0;i<300000;i++);
							}
						}
		//switch 4 and 4 LED's
		if(!(GPIOA_IDR &=(1<<15))){
							for(i=0;i<300000;i++){
								if(!(GPIOA_IDR &=(1<<15))){
									GPIOC_ODR ^=(1<<6);
									GPIOB_ODR ^=(1<<15);
									GPIOB_ODR ^=(1<<14);
									GPIOB_ODR ^=(1<<13);
								}
								for(i=0;i<300000;i++);
							}
		}
	}
}


